### ISSUE TITLE
Ocr wont work in a simple image

### ISSUE THREAD

**Issue by einer20** [karisigurd4/DocumentLab#1]
First of all let me say that i love this concept of OCR.

But I'm having a hard time making it work with a simple image to extract a number. Here's is what im doing and the output:

![Untitled3](https://user-images.githubusercontent.com/3115567/100254064-3d5a9800-2f18-11eb-9c62-9bd4ed5a3fb6.png)

I'm trying to extract the number that is after the text "FACTURA NO." but the result is always empty.
Here is the script:
```
InvoiceNum:
Text(FACTURA NO.) Right [Number];
```
Here is the original image:
![e](https://user-images.githubusercontent.com/3115567/100254210-64b16500-2f18-11eb-84a8-d682883e2740.PNG)

Can you point out what i'm doing wrong?

**Comment by einer20** [comment]
I also tried the image that you published as example and it did not work neither:

![Untitled3](https://user-images.githubusercontent.com/3115567/100256761-8c55fc80-2f1b-11eb-8755-c36219882757.png)

**Comment by karisigurd4** [comment]
Hey! Thanks for testing it and reaching out, I'm happy to help! 

I guess this is a quirk but images sent in need to be within a certain size range so that the analysis goes smoothly. I should add a note about that ...

You can use my fake invoice from [here](https://github.com/karisigurd4/DocumentLab/blob/master/Test/DocumentLab.Test/Data/fakeinvoice.png) for reference but I scaled down your image to relative size:
![Test](https://user-images.githubusercontent.com/11043522/100264594-f041ea80-2f46-11eb-8fd3-8a152ee4b414.png)

And then ran the script on it:
![Test1](https://user-images.githubusercontent.com/11043522/100264688-123b6d00-2f47-11eb-9c6f-3ecd5a1c0c12.PNG)

A bit of a pre-processing step there.

**Comment by einer20** [comment]
Hi @karisigurd4,
I made more testing and realized the image size range also matters. Should definitely put a note about it.

**Comment by karisigurd4** [comment]
I've added a note about this one under "Getting started" in the readme which hopefully will suffice for now. Thank you for the input and feel free to stay in touch if you need any more help!
